import asyncio
import logging
import re
from dataclasses import dataclass

from config import Settings
from agent import run_agent, push_branch, get_diff
from reviewer import run_review
from platforms import create_platform

logger = logging.getLogger(__name__)


@dataclass
class Job:
    platform: str
    issue_number: int
    title: str
    body: str


_queue: asyncio.Queue = asyncio.Queue()


async def enqueue_job(*, platform: str, issue_number: int, title: str, body: str) -> None:
    await _queue.put(Job(platform=platform, issue_number=issue_number, title=title, body=body))
    logger.info("Enqueued issue #%d (%s)", issue_number, platform)


async def start_worker(settings: Settings) -> None:
    logger.info("Worker started")
    while True:
        job = await _queue.get()
        try:
            await _process_job(job, settings)
        except Exception as exc:
            logger.exception("Unhandled error for issue #%d", job.issue_number)
            try:
                platform = create_platform(settings)
                platform.post_comment(
                    job.issue_number,
                    f"AI workflow encountered an unexpected error: {exc}",
                )
            except Exception:
                logger.exception("Failed to post error comment for issue #%d", job.issue_number)
        finally:
            _queue.task_done()


async def _process_job(job: Job, settings: Settings) -> None:
    platform = create_platform(settings)
    branch = f"ai/issue-{job.issue_number}-{_slugify(job.title)}"
    logger.info("Processing issue #%d on branch %s", job.issue_number, branch)

    platform.post_comment(
        job.issue_number,
        f"**AI coding workflow started**\n\nWorking on branch `{branch}`. "
        f"Cloning repo and running AI agent — this may take a few minutes.",
    )

    success, repo_path, initial_commit, error_msg = await asyncio.to_thread(
        run_agent,
        issue_number=job.issue_number,
        issue_title=job.title,
        issue_body=job.body,
        branch=branch,
        settings=settings,
    )

    if not success:
        platform.post_comment(
            job.issue_number,
            f"**AI coding workflow failed**\n\n"
            f"Could not produce passing tests after {settings.max_retries} attempts.\n\n"
            f"Last test output:\n```\n{error_msg}\n```",
        )
        return

    diff = get_diff(repo_path, initial_commit)
    if not diff.strip():
        platform.post_comment(
            job.issue_number,
            "**AI coding workflow completed — no changes made**\n\n"
            "The AI processed this issue but made no code changes. "
            "Please add more detail or a concrete example to the issue description.",
        )
        return

    platform.post_comment(
        job.issue_number,
        "**AI coding workflow — changes ready**\n\nCode changes complete. Pushing branch and creating PR...",
    )

    await asyncio.to_thread(push_branch, repo_path, branch, settings)

    pr_title = f"fix: {job.title} (resolves #{job.issue_number})"
    pr_body = (
        f"Closes #{job.issue_number}\n\n"
        f"This PR was automatically generated by the AI coding workflow."
    )
    pr_url = platform.create_pr(branch, pr_title, pr_body)
    logger.info("Created PR/MR: %s", pr_url)

    platform.post_comment(
        job.issue_number,
        f"**PR created:** {pr_url}\n\nRunning AI code review...",
    )

    review_comment = await asyncio.to_thread(
        run_review,
        issue_title=job.title,
        issue_body=job.body,
        diff=diff,
        settings=settings,
    )
    platform.post_comment(
        job.issue_number,
        f"**AI code review complete**\n\n{review_comment}",
    )
    logger.info("Posted review comment for issue #%d", job.issue_number)


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:50]
